## Import all the required libraries

In [1]:
import pandas as pd
import numpy as np

from scipy import stats
from scipy.stats import norm

import math
from scipy.stats import chi2_contingency
from scipy.stats import chi2

import warnings
warnings.filterwarnings('ignore')

## Q1

In [2]:
cutlets=pd.read_csv('Cutlets.csv')
cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [3]:
unitA=pd.Series(cutlets.iloc[:,0])
unitA.head(2)

0    6.8090
1    6.4376
Name: Unit A, dtype: float64

In [4]:
unitB=pd.Series(cutlets.iloc[:,1])
unitB.head(2)

0    6.7703
1    7.5093
Name: Unit B, dtype: float64

In [5]:
#Null hyposthesis as Ho: μ1 = μ2 (There is no difference in diameters of cutlets between two units)
#Alternate hypothesis as Ha: μ1 ≠ μ2 (There is significant difference in diameters of cutlets between two units)

#2 Sample 2 Tail test applicable

# 2-sample 2-tail ttest:   stats.ttest_ind(array1,array2)     # ind -> independent samples
Ttest_ind=stats.ttest_ind(unitA,unitB)
print(Ttest_ind)
print()
p_value = Ttest_ind[1]

alpha = 0.05
if p_value > alpha:
    print("Accept Null Hypothesis | There is no difference in diameters of cutlets between two units")
else:
    print("Accept Alternate Hypothesis | There is significant difference in diameters of cutlets between two units")

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.47223947245995)

Accept Null Hypothesis | There is no difference in diameters of cutlets between two units


## Q2

In [6]:
LabTat = pd.read_csv("LabTAT.csv")
LabTat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [7]:
#Null Hypothesis Ho: μ1 = μ2 (No Varaince: All samples TAT population means are same)
#Alternate Hypothesis Ha: μ1 ≠ μ2 (It has Variance: Atleast one sample TAT population mean is different)

#Anova ftest statistics: Analysis of varaince between more than 2 samples or columns

anova = stats.f_oneway(LabTat.iloc[:,0],LabTat.iloc[:,1],LabTat.iloc[:,2],LabTat.iloc[:,3])
print(anova)
print()
p_value = anova[1]
alpha = 0.05
if p_value > alpha:
    print("Accept Null Hypothesis | There is no varaince means all samples TAT population means are same")
else:
    print("Accept Alternate Hypothesis | There is variance atleast one sample TAT population mean is different")
    


F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

Accept Alternate Hypothesis | There is variance atleast one sample TAT population mean is different


## Q3

In [8]:
br = pd.read_csv("BuyerRatio.csv")
br

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [9]:
br=br.drop(['Observed Values'], axis=1)
br

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [10]:
Males = br.iloc[0]
Females = br.iloc[1]

In [11]:
Males = np.array(Males)
Females = np.array(Females)

In [12]:
observed_values = np.array([Males,Females])
print(observed_values)
print()
values = chi2_contingency(observed_values)
print(values)
print()
p_value=chi2_contingency(observed_values)[1]
print(p_value)
print()
alpha = 0.05
if p_value > alpha:
    print("Accept Null Hypothesis | Male and female buyers are similar across in region")
else:
    print("Accept Alternate Hypothesis | There is no Male and female buyers are similar across in region")

[[  50  142  131   70]
 [ 435 1523 1356  750]]

(1.595945538661058, 0.6603094907091882, 3, array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

0.6603094907091882

Accept Null Hypothesis | Male and female buyers are similar across in region


## Q4

In [13]:
co=pd.read_csv('Costomer+OrderForm.csv')
co.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [14]:
co['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [15]:
co['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [16]:
co['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [17]:
co['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [18]:
#Null Hypothesis Ho:μ1 = μ2 Independence of categorical variables (customer order forms defective % does not varies by centre) 
#Alternative hypothesis Ha:μ1 ≠ μ2 Dependence of categorical variables (customer order forms defective % varies by centre)
# Make a contingency table
# In statistics, a contingency table (also known as a cross tabulation or crosstab) is a type of 
# table in a matrix format that displays the (multivariate) frequency distribution of the variables.
crosstab=np.array([[271,267,269,280],[29,33,31,20]])
crosstab

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [19]:
# stats value
# p_value
# dof
# expected_frq
chi2_contingency(crosstab) 

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [21]:
if 0.2771 > 0.05:
    print("Accept Null Hypothesis | customer order forms defective % does not varies by centre")
else:
    print("Accept Alternate Hypothesis | There is no Male and female buyers are similar across in region")

Accept Null Hypothesis | customer order forms defective % does not varies by centre
